### ISSUE TITLE
After upgrading to version 0.3.7, an error occurs.

### ISSUE THREAD

**Issue by dabaolyy** [jridgewell/sourcemaps#23]
![image](https://github.com/user-attachments/assets/208ce0fd-24d7-4014-8070-650bbee7f42a)
2024-12-10T11:32:35.614013190Z [?25l[36m⠋[39m  Building for production...[2K[1G[?25h[32m✔[39m  Building for production...
2024-12-10T11:32:35.614071342Z [41m ERROR [49m [31mSyntaxError: Unexpected token '||='[39m
2024-12-10T11:32:35.614080322Z /data/space/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js:1328
2024-12-10T11:32:35.614087347Z             const originalLine = originalSource[sourceLine] ||= [];
2024-12-10T11:32:35.614093650Z                                                             ^^^
2024-12-10T11:32:35.614099870Z 
2024-12-10T11:32:35.614105820Z SyntaxError: Unexpected token '||='
2024-12-10T11:32:35.614127780Z     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
2024-12-10T11:32:35.614134483Z     at Module._compile (internal/modules/cjs/loader.js:1049:27)
2024-12-10T11:32:35.614141043Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2024-12-10T11:32:35.614147470Z     at Module.load (internal/modules/cjs/loader.js:950:32)
2024-12-10T11:32:35.614153505Z     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2024-12-10T11:32:35.614159460Z     at Module.require (internal/modules/cjs/loader.js:974:19)
2024-12-10T11:32:35.614165450Z     at require (internal/modules/cjs/helpers.js:101:18)
2024-12-10T11:32:35.614171420Z     at Object.<anonymous> (/data/space/node_modules/@babel/generator/lib/source-map.js:7:19)
2024-12-10T11:32:35.614177725Z     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2024-12-10T11:32:35.614183708Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2024-12-10T11:32:35.614189645Z     at Module.load (internal/modules/cjs/loader.js:950:32)
2024-12-10T11:32:35.614195700Z     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2024-12-10T11:32:35.614201757Z     at Module.require (internal/modules/cjs/loader.js:974:19)
2024-12-10T11:32:35.614207880Z     at require (internal/modules/cjs/helpers.js:101:18)
2024-12-10T11:32:35.614213968Z     at Object.<anonymous> (/data/space/node_modules/@babel/generator/lib/index.js:7:18)
2024-12-10T11:32:35.614220165Z     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2024-12-10T11:32:35.614227027Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2024-12-10T11:32:35.614233181Z     at Module.load (internal/modules/cjs/loader.js:950:32)
2024-12-10T11:32:35.614239170Z     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2024-12-10T11:32:35.614245246Z     at Module.require (internal/modules/cjs/loader.js:974:19)
2024-12-10T11:32:35.614251180Z     at require (internal/modules/cjs/helpers.js:101:18)
2024-12-10T11:32:35.614257210Z     at Object.<anonymous> (/data/space/node_modules/@babel/traverse/lib/path/index.js:14:18)
2024-12-10T11:32:35.614263388Z     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2024-12-10T11:32:35.614269223Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2024-12-10T11:32:35.614276351Z     at Module.load (internal/modules/cjs/loader.js:950:32)
2024-12-10T11:32:35.614282642Z     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

**Comment by dabaolyy** [comment]
The Node.js version is v14.19.1. Due to project requirements, we cannot upgrade Node.js arbitrarily. Please assist in making the application compatible with this version of Node.js

**Comment by femke77** [comment]
> The Node.js version is v14.19.1. Due to project requirements, we cannot upgrade Node.js arbitrarily. Please assist in making the application compatible with this version of Node.js

Can you role back to 0.3.5? that worked for us last night.
