### ISSUE TITLE
Error: [BABEL]: Cannot find module '...\\node_modules\\@jridgewell\\gen-mapping\\dist\\gen-mapping.umd.js

### ISSUE THREAD

**Issue by aram88888** [jridgewell/sourcemaps#8]
Hi just getting error message. I think it is because your new update.

**Comment by inzanez** [comment]
Same here, also getting this message from NPM:

`npm warn deprecated @jridgewell/gen-mapping@0.3.6: publish failed to build the dist directory`

**Comment by natlibfi-jonollil** [comment]
Same. I tested just downloading the package and building it:
```
[main]@sourcemaps: npm run build

> build
> turbo run build


Attention:
Turborepo now collects completely anonymous telemetry regarding usage.
This information is used to shape the Turborepo roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://turbo.build/repo/docs/telemetry

turbo 2.3.1

• Packages in scope: @jridgewell/gen-mapping, @jridgewell/remapping, @jridgewell/source-map, @jridgewell/sourcemap-codec, @jridgewell/trace-mapping
• Running build in 5 packages
• Remote caching disabled
@jridgewell/sourcemap-codec:build: cache miss, executing aae99798de8f7ece
@jridgewell/sourcemap-codec:build: 
@jridgewell/sourcemap-codec:build: 
@jridgewell/sourcemap-codec:build: > @jridgewell/sourcemap-codec@1.5.0 build
@jridgewell/sourcemap-codec:build: > run-s -n build:code build:types
@jridgewell/sourcemap-codec:build: 

@jridgewell/sourcemap-codec:build: > @jridgewell/sourcemap-codec@1.5.0 build:code /home/xxxxx/sourcemaps/packages/sourcemap-codec/package.json
@jridgewell/sourcemap-codec:build: > UMD=sourcemapCodec node ../../esbuild.mjs sourcemap-codec.ts 
@jridgewell/sourcemap-codec:build: 
@jridgewell/sourcemap-codec:build: 
@jridgewell/sourcemap-codec:build: > @jridgewell/sourcemap-codec@1.5.0 build:code
@jridgewell/sourcemap-codec:build: > UMD=sourcemapCodec node ../../esbuild.mjs sourcemap-codec.ts
@jridgewell/sourcemap-codec:build: 
Compiled umd {
@jridgewell/sourcemap-codec:build:   errors: [],
@jridgewell/sourcemap-codec:build:   warnings: [],
@jridgewell/sourcemap-codec:build:   outputFiles: undefined,
@jridgewell/sourcemap-codec:build:   metafile: undefined,
@jridgewell/sourcemap-codec:build:   mangleCache: undefined
@jridgewell/sourcemap-codec:build: }
@jridgewell/sourcemap-codec:build: Compiled esm {
@jridgewell/sourcemap-codec:build:   errors: [],
@jridgewell/sourcemap-codec:build:   warnings: [],
@jridgewell/sourcemap-codec:build:   outputFiles: undefined,
@jridgewell/sourcemap-codec:build:   metafile: undefined,
@jridgewell/sourcemap-codec:build:   mangleCache: undefined
@jridgewell/sourcemap-codec:build: }

@jridgewell/sourcemap-codec:build: > @jridgewell/sourcemap-codec@1.5.0 build:types /home/xxxxx/sourcemaps/packages/sourcemap-codec/package.json
@jridgewell/sourcemap-codec:build: > tsc --project tsconfig.build.json 
@jridgewell/sourcemap-codec:build: 
@jridgewell/sourcemap-codec:build: 
@jridgewell/sourcemap-codec:build: > @jridgewell/sourcemap-codec@1.5.0 build:types
@jridgewell/sourcemap-codec:build: > tsc --project tsconfig.build.json
@jridgewell/sourcemap-codec:build: 

@jridgewell/trace-mapping:build: cache miss, executing 8f61a7b928481af4
@jridgewell/trace-mapping:build: 
@jridgewell/trace-mapping:build: 
@jridgewell/trace-mapping:build: > @jridgewell/trace-mapping@0.3.25 build
@jridgewell/trace-mapping:build: > run-s -n build:code build:types
@jridgewell/trace-mapping:build: 

@jridgewell/trace-mapping:build: > @jridgewell/trace-mapping@0.3.25 build:code /home/xxxxx/sourcemaps/packages/trace-mapping/package.json
@jridgewell/trace-mapping:build: > UMD=sourcemapCodec node ../../esbuild.mjs trace-mapping.ts 
@jridgewell/trace-mapping:build: 
@jridgewell/trace-mapping:build: 
@jridgewell/trace-mapping:build: > @jridgewell/trace-mapping@0.3.25 build:code
@jridgewell/trace-mapping:build: > UMD=sourcemapCodec node ../../esbuild.mjs trace-mapping.ts
@jridgewell/trace-mapping:build: 
Compiled esm {
@jridgewell/trace-mapping:build:   errors: [],
@jridgewell/trace-mapping:build:   warnings: [],
@jridgewell/trace-mapping:build:   outputFiles: undefined,
@jridgewell/trace-mapping:build:   metafile: undefined,
@jridgewell/trace-mapping:build:   mangleCache: undefined
@jridgewell/trace-mapping:build: }
@jridgewell/trace-mapping:build: Compiled umd {
@jridgewell/trace-mapping:build:   errors: [],
@jridgewell/trace-mapping:build:   warnings: [],
@jridgewell/trace-mapping:build:   outputFiles: undefined,
@jridgewell/trace-mapping:build:   metafile: undefined,
@jridgewell/trace-mapping:build:   mangleCache: undefined
@jridgewell/trace-mapping:build: }

@jridgewell/trace-mapping:build: > @jridgewell/trace-mapping@0.3.25 build:types /home/xxxxx/sourcemaps/packages/trace-mapping/package.json
@jridgewell/trace-mapping:build: > tsc --project tsconfig.build.json 
@jridgewell/trace-mapping:build: 
@jridgewell/trace-mapping:build: 
@jridgewell/trace-mapping:build: > @jridgewell/trace-mapping@0.3.25 build:types
@jridgewell/trace-mapping:build: > tsc --project tsconfig.build.json
@jridgewell/trace-mapping:build: 

@jridgewell/remapping:build: cache miss, executing 8501a0e0e5b50aa1
@jridgewell/remapping:build: 
@jridgewell/gen-mapping:build: cache miss, executing a2412189d27f923a
@jridgewell/gen-mapping:build: 
@jridgewell/source-map:build: cache miss, executing 111e8e07d8248842
@jridgewell/source-map:build: 
@jridgewell/remapping:build: 
@jridgewell/remapping:build: > @jridgewell/remapping@2.3.0 build
@jridgewell/remapping:build: > run-s -n build:code build:types
@jridgewell/remapping:build: 
@jridgewell/gen-mapping:build: 
@jridgewell/source-map:build: 
@jridgewell/gen-mapping:build: > @jridgewell/gen-mapping@0.3.6-beta.4 build
@jridgewell/source-map:build: > @jridgewell/source-map@0.3.6 build
@jridgewell/gen-mapping:build: > run-s -n build:code build:types
@jridgewell/source-map:build: > run-s -n build:code build:types
@jridgewell/gen-mapping:build: 
@jridgewell/source-map:build: 

@jridgewell/remapping:build: > @jridgewell/remapping@2.3.0 build:code /home/xxxxx/sourcemaps/packages/remapping/package.json
@jridgewell/remapping:build: > UMD=sourcemapCodec node ../../esbuild.mjs remapping.ts 
@jridgewell/remapping:build: 

@jridgewell/gen-mapping:build: > @jridgewell/gen-mapping@0.3.6-beta.4 build:code /home/xxxxx/sourcemaps/packages/gen-mapping/package.json
@jridgewell/gen-mapping:build: > UMD=sourcemapCodec node ../../esbuild.mjs gen-mapping.ts 
@jridgewell/gen-mapping:build: 

@jridgewell/source-map:build: > @jridgewell/source-map@0.3.6 build:code /home/xxxxx/sourcemaps/packages/source-map/package.json
@jridgewell/source-map:build: > UMD=sourcemapCodec node ../../esbuild.mjs source-map.ts 
@jridgewell/source-map:build: 
@jridgewell/source-map:build: 
@jridgewell/source-map:build: > @jridgewell/source-map@0.3.6 build:code
@jridgewell/source-map:build: > UMD=sourcemapCodec node ../../esbuild.mjs source-map.ts
@jridgewell/source-map:build: 
@jridgewell/gen-mapping:build: 
@jridgewell/gen-mapping:build: > @jridgewell/gen-mapping@0.3.6-beta.4 build:code
@jridgewell/gen-mapping:build: > UMD=sourcemapCodec node ../../esbuild.mjs gen-mapping.ts
@jridgewell/gen-mapping:build: 
@jridgewell/remapping:build: 
@jridgewell/remapping:build: > @jridgewell/remapping@2.3.0 build:code
@jridgewell/remapping:build: > UMD=sourcemapCodec node ../../esbuild.mjs remapping.ts
@jridgewell/remapping:build: 
✘ [ERROR] Could not resolve "@jridgewell/gen-mapping"
@jridgewell/source-map:build: 
@jridgewell/source-map:build:     src/source-map.ts:17:7:
@jridgewell/source-map:build:       17 │ } from '@jridgewell/gen-mapping';
@jridgewell/source-map:build:          ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/source-map:build: 
@jridgewell/source-map:build:   The module "./dist/gen-mapping.umd.js" was not found on the file system:
@jridgewell/source-map:build: 
@jridgewell/source-map:build:     node_modules/@jridgewell/gen-mapping/package.json:21:19:
@jridgewell/source-map:build:       21 │         "browser": "./dist/gen-mapping.umd.js",
@jridgewell/source-map:build:          ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/source-map:build: 
@jridgewell/source-map:build:   You can mark the path "@jridgewell/gen-mapping" as external to exclude it from
@jridgewell/source-map:build:   the bundle, which will remove this error and leave the unresolved path in the
@jridgewell/source-map:build:   bundle.
@jridgewell/source-map:build: 
@jridgewell/source-map:build: ✘ [ERROR] Could not resolve "@jridgewell/gen-mapping"
@jridgewell/source-map:build: 
@jridgewell/source-map:build:     src/source-map.ts:17:7:
@jridgewell/source-map:build:       17 │ } from '@jridgewell/gen-mapping';
@jridgewell/source-map:build:          ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/source-map:build: 
@jridgewell/source-map:build:   The module "./dist/gen-mapping.umd.js" was not found on the file system:
@jridgewell/source-map:build: 
@jridgewell/source-map:build:     node_modules/@jridgewell/gen-mapping/package.json:21:19:
@jridgewell/source-map:build:       21 │         "browser": "./dist/gen-mapping.umd.js",
@jridgewell/source-map:build:          ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/source-map:build: 
@jridgewell/source-map:build:   You can mark the path "@jridgewell/gen-mapping" as external to exclude it from
@jridgewell/source-map:build:   the bundle, which will remove this error and leave the unresolved path in the
@jridgewell/source-map:build:   bundle.
@jridgewell/source-map:build: 
✘ [ERROR] Could not resolve "@jridgewell/gen-mapping"
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     src/source-map.ts:1:43:
@jridgewell/remapping:build:       1 │ import { toDecodedMap, toEncodedMap } from '@jridgewell/gen-mapping';
@jridgewell/remapping:build:         ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   The module "./dist/gen-mapping.umd.js" was not found on the file system:
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     node_modules/@jridgewell/gen-mapping/package.json:21:19:
@jridgewell/remapping:build:       21 │         "browser": "./dist/gen-mapping.umd.js",
@jridgewell/remapping:build:          ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   You can mark the path "@jridgewell/gen-mapping" as external to exclude it from
@jridgewell/remapping:build:   the bundle, which will remove this error and leave the unresolved path in the
@jridgewell/remapping:build:   bundle.
@jridgewell/remapping:build: 
@jridgewell/remapping:build: ✘ [ERROR] Could not resolve "@jridgewell/gen-mapping"
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     src/source-map-tree.ts:1:73:
@jridgewell/remapping:build:       1 │ ...ment, setIgnore, setSourceContent } from '@jridgewell/gen-mapping';
@jridgewell/remapping:build:         ╵                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   The module "./dist/gen-mapping.umd.js" was not found on the file system:
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     node_modules/@jridgewell/gen-mapping/package.json:21:19:
@jridgewell/remapping:build:       21 │         "browser": "./dist/gen-mapping.umd.js",
@jridgewell/remapping:build:          ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   You can mark the path "@jridgewell/gen-mapping" as external to exclude it from
@jridgewell/remapping:build:   the bundle, which will remove this error and leave the unresolved path in the
@jridgewell/remapping:build:   bundle.
@jridgewell/remapping:build: 
@jridgewell/source-map:build: /home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:1476
@jridgewell/source-map:build:   let error = new Error(text);
@jridgewell/source-map:build:               ^
@jridgewell/source-map:build: 
@jridgewell/source-map:build: Error: Build failed with 1 error:
@jridgewell/source-map:build: src/source-map.ts:17:7: ERROR: Could not resolve "@jridgewell/gen-mapping"
@jridgewell/source-map:build:     at failureErrorWithLog (/home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:1476:15)
@jridgewell/source-map:build:     at /home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:945:25
@jridgewell/source-map:build:     at /home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:1354:9
@jridgewell/source-map:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
@jridgewell/source-map:build:   errors: [Getter/Setter],
@jridgewell/source-map:build:   warnings: [Getter/Setter]
@jridgewell/source-map:build: }
@jridgewell/source-map:build: 
@jridgewell/source-map:build: Node.js v20.17.0
@jridgewell/remapping:build: ✘ [ERROR] Could not resolve "@jridgewell/gen-mapping"
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     src/source-map.ts:1:43:
@jridgewell/remapping:build:       1 │ import { toDecodedMap, toEncodedMap } from '@jridgewell/gen-mapping';
@jridgewell/remapping:build:         ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   The module "./dist/gen-mapping.umd.js" was not found on the file system:
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     node_modules/@jridgewell/gen-mapping/package.json:21:19:
@jridgewell/remapping:build:       21 │         "browser": "./dist/gen-mapping.umd.js",
@jridgewell/remapping:build:          ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   You can mark the path "@jridgewell/gen-mapping" as external to exclude it from
@jridgewell/remapping:build:   the bundle, which will remove this error and leave the unresolved path in the
@jridgewell/remapping:build:   bundle.
@jridgewell/remapping:build: 
@jridgewell/remapping:build: ✘ [ERROR] Could not resolve "@jridgewell/gen-mapping"
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     src/source-map-tree.ts:1:73:
@jridgewell/remapping:build:       1 │ ...ment, setIgnore, setSourceContent } from '@jridgewell/gen-mapping';
@jridgewell/remapping:build:         ╵                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   The module "./dist/gen-mapping.umd.js" was not found on the file system:
@jridgewell/remapping:build: 
@jridgewell/remapping:build:     node_modules/@jridgewell/gen-mapping/package.json:21:19:
@jridgewell/remapping:build:       21 │         "browser": "./dist/gen-mapping.umd.js",
@jridgewell/remapping:build:          ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
@jridgewell/remapping:build: 
@jridgewell/remapping:build:   You can mark the path "@jridgewell/gen-mapping" as external to exclude it from
@jridgewell/remapping:build:   the bundle, which will remove this error and leave the unresolved path in the
@jridgewell/remapping:build:   bundle.
@jridgewell/remapping:build: 
@jridgewell/remapping:build: /home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:1476
@jridgewell/remapping:build:   let error = new Error(text);
@jridgewell/remapping:build:               ^
@jridgewell/remapping:build: 
@jridgewell/remapping:build: Error: Build failed with 2 errors:
@jridgewell/remapping:build: src/source-map-tree.ts:1:73: ERROR: Could not resolve "@jridgewell/gen-mapping"
@jridgewell/remapping:build: src/source-map.ts:1:43: ERROR: Could not resolve "@jridgewell/gen-mapping"
@jridgewell/remapping:build:     at failureErrorWithLog (/home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:1476:15)
@jridgewell/remapping:build:     at /home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:945:25
@jridgewell/remapping:build:     at /home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:897:52
@jridgewell/remapping:build:     at buildResponseToResult (/home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:943:7)
@jridgewell/remapping:build:     at /home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:970:16
@jridgewell/remapping:build:     at responseCallbacks.<computed> (/home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:622:9)
@jridgewell/remapping:build:     at handleIncomingPacket (/home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:677:12)
@jridgewell/remapping:build:     at Socket.readFromStdout (/home/xxxxx/sourcemaps/node_modules/esbuild/lib/main.js:600:7)
@jridgewell/remapping:build:     at Socket.emit (node:events:519:28)
@jridgewell/remapping:build:     at addChunk (node:internal/streams/readable:559:12) {
@jridgewell/remapping:build:   errors: [Getter/Setter],
@jridgewell/remapping:build:   warnings: [Getter/Setter]
@jridgewell/remapping:build: }
@jridgewell/remapping:build: 
@jridgewell/remapping:build: Node.js v20.17.0
npm error Lifecycle script `build:code` failed with error:
npm error code 1
npm error path /home/xxxxx/sourcemaps/packages/source-map
npm error workspace @jridgewell/source-map@0.3.6
npm error location /home/xxxxx/sourcemaps/packages/source-map
npm error command failed
npm error command sh -c UMD=sourcemapCodec node ../../esbuild.mjs source-map.ts
Compiled esm {
@jridgewell/gen-mapping:build:   errors: [],
@jridgewell/gen-mapping:build:   warnings: [],
@jridgewell/gen-mapping:build:   outputFiles: undefined,
@jridgewell/gen-mapping:build:   metafile: undefined,
@jridgewell/gen-mapping:build:   mangleCache: undefined
@jridgewell/gen-mapping:build: }
@jridgewell/gen-mapping:build: Compiled umd {
@jridgewell/gen-mapping:build:   errors: [],
@jridgewell/gen-mapping:build:   warnings: [],
@jridgewell/gen-mapping:build:   outputFiles: undefined,
@jridgewell/gen-mapping:build:   metafile: undefined,
@jridgewell/gen-mapping:build:   mangleCache: undefined
@jridgewell/gen-mapping:build: }
npm error Lifecycle script `build:code` failed with error:
npm error code 1
npm error path /home/xxxxx/sourcemaps/packages/remapping
npm error workspace @jridgewell/remapping@2.3.0
npm error location /home/xxxxx/sourcemaps/packages/remapping
npm error command failed
npm error command sh -c UMD=sourcemapCodec node ../../esbuild.mjs remapping.ts
ERROR: "build:code" exited with 1.
ERROR: "build:code" exited with 1.
npm error Lifecycle script `build` failed with error:
npm error code 1

@jridgewell/gen-mapping:build: > @jridgewell/gen-mapping@0.3.6-beta.4 build:types /home/xxxxx/sourcemaps/packages/gen-mapping/package.json
@jridgewell/gen-mapping:build: > tsc --project tsconfig.build.json 
@jridgewell/gen-mapping:build: 
npm error path /home/xxxxx/sourcemaps/packages/source-map
npm error workspace @jridgewell/source-map@0.3.6
npm error location /home/xxxxx/sourcemaps/packages/source-map
npm error command failed
npm error command sh -c run-s -n build:code build:types
npm error Lifecycle script `build` failed with error:
npm error code 1
npm error path /home/xxxxx/sourcemaps/packages/remapping
npm error workspace @jridgewell/remapping@2.3.0
npm error location /home/xxxxx/sourcemaps/packages/remapping
npm error command failed
npm error command sh -c run-s -n build:code build:types

@jridgewell/source-map:build: ERROR: command finished with error: command (/home/xxxxx/sourcemaps/packages/source-map) /usr/local/bin/npm run build exited (1)
⠙
@jridgewell/source-map#build: command (/home/xxxxx/sourcemaps/packages/source-map) /usr/local/bin/npm run build exited (1)

 Tasks:    2 successful, 5 total
Cached:    0 cached, 5 total
  Time:    4.766s 
Failed:    @jridgewell/source-map#build

 ERROR  run failed: command  exited (1)
```

**Comment by sharbel93** [comment]
<img width="414" alt="image" src="https://github.com/user-attachments/assets/13d7cc19-4d03-4e77-9eec-9df533989a19">
same here

**Comment by vitor3g** [comment]
still continues, even with override

**Comment by xyzith** [comment]
same error here

**Comment by gargut-deshaw** [comment]
Same here.

**Comment by tyrann0us** [comment]
Guys, check the closed GitHub issues. This is known and fixed!

**Comment by vitor3g** [comment]
> Guys, check the closed GitHub issues. This is known and fixed!

The issue has been fixed if you're downloading the package directly, but if you're behind a Babel setup, the problem still persists.

**Comment by kerm1it** [comment]
should you publish 0.3.7 to fix it ？

**Comment by kerm1it** [comment]
Or you should change the latest tag to point to 0.3.5？

**Comment by kaijietti** [comment]
> Or you should change the latest tag to point to 0.3.5？

+1

**Comment by aram88888** [comment]
Still showing 0.3.6 https://www.npmjs.com/package/@jridgewell/source-map

**Comment by jridgewell** [comment]
> Or you should change the latest tag to point to 0.3.5？

Done.
